### ISSUE TITLE
The provided token has expired.

### ISSUE THREAD

**Issue by kokayin** [Ifan24/GPT_Subtitler#1]
after upload a srt with invalid timestamp, the error msg show:The provided token has expired.
invalid timestamp is usually not a problem to process to the translation page, i.e. one more "0" in ms, but i have no idea how this "The provided token has expired." error show up. this is the first time.
please help.

**Comment by Ifan24** [comment]
Hi,
Thanks for reporting this. The "ExpiredToken" error usually means your session has timed out.To fix:

1. Refresh the page and try uploading again.

If that doesn't work:
1. Log out
2. Log back in
3. Try uploading again

If the problem persists, please clear your browser cache and cookies, then repeat the steps above.

**Comment by kokayin** [comment]
problem is solved. thanks.
First, i try https://capcut-srt-export.vogelcodes.com/ to output .srt from json of capcut, but the file is invalid
Then i try https://xstar.me/JianyingSRT/ to output .srt and there is no "invalid timestamp" and no  "ExpiredToken" error.
So wired for these two error linked up together, maybe just by chance it happened.
Also, after i pay for the PRO account on Capcut to do a test, the .srt is clean is usable, no error.

Report for measure that i did: i had already done 1-2-3(i.e. logout-login-upload) but problem was not solved from vogelcodes's .srt

Anyway, congrats to start on product hunt! will write a positive review later!
