### ISSUE TITLE
Failed to claim daily reward. Please try again.

### ISSUE THREAD

**Issue by kokayin** [Ifan24/GPT_Subtitler#2]
Failed to claim daily reward. Please try again.
failed to claim daily reward and msg showed for two days.
had try to logout and login.
did anyone have the same issue?

**Comment by Ifan24** [comment]
Hi, I just adjusted the ReCaptcha threshold to make it easier for genuine users to claim daily rewards. You should be able to claim the daily reward now. If there are still issues, please try to disable the VPN or use a different internet connection. Sorry about the inconvenience.
