### ISSUE TITLE
多次出现在剧集大约3/4处字幕顺序时间出现比较大的混淆

### ISSUE THREAD

**Issue by Eureka321** [Ifan24/GPT_Subtitler#3]
使用40-mini或者gemini-pro，多次在节目大概1/2-3/4处出现字幕较为严重的错误，表现为顺序颠倒，内容不相关等。重新翻译则会好转，不知能否排查原因并优化？

**Comment by Ifan24** [comment]
感谢反馈！这个问题可能有以下几个原因：

1. **批次连接处理机制**
目前系统会在每个批次中包含上一批次的最后一句（原文+译文）和下一批次的第一句原文，目的是确保翻译的连贯性。但这个机制有时可能会导致错位，比如把最后一句和下一批次一起翻译，造成整体顺序偏移。

2. **上下文记忆影响**
启用上下文记忆后，如果某个批次出现了轻微错误，可能会通过上下文传递影响到后续批次，形成错误累积。

3. **批次处理独立性**
一般来说出现错误的地方是随机的，因为每个批次设计上是独立处理的，错误在1/2-3/4处较为集中可能和上述因素和模型幻觉叠加有关，去掉那些功能让每个批次真正独立处理可能会改善一些

**预计可以这样解决：**
1. 下个版本我会把批次连接机制做成可设置项：
   - 可以设置上下批次的关联句数（0-N）
   - 默认设置为0完全关闭此功能

2. 对于上下文记忆：
   - 建议可以尝试减小上下文窗口大小，降低错误传递的可能性
   - 如果使用场景中模型能较好地处理专有名词，不太需要记住之前是怎么翻译的，可以考虑关闭这个功能
