### ISSUE TITLE
the redemption code after Feedback Survey is not available

### ISSUE THREAD

**Issue by dilotec-2015** [Ifan24/GPT_Subtitler#4]
hi,
the redemption code is not available after i submitted the
"GPT Subtitler User Feedback Survey"
what i see is :

![grafik](https://github.com/user-attachments/assets/6b15295c-1001-43b7-814b-01358cff9ddc)

there is no code, i see the string "GPT_subtitler_google_form"

please fix it

**Comment by Ifan24** [comment]
Hi there,

Could you tell me more about what you're seeing? You should be able to use the string "GPT_subtitler_google_form" in the setting page as your redeem code.

**Comment by dilotec-2015** [comment]
thanks for the information.  I didn't even try to use "GPT_subtitler_google_form" as the code because it looks like an error on the page. but actually, it worked. I expected a code like "SURVEY321" or something similar :). Thank you.

**Comment by thaikolja** [comment]
@Ifan24 However, now, the GitHub README.md code "has expired." This should either be removed or updated :)

**Comment by Ifan24** [comment]
> [@Ifan24](https://github.com/Ifan24) However, now, the GitHub README.md code "has expired." This should either be removed or updated :)

@thaikolja Thanks for reminding me about this. I just updated the expiry date for that code
